<div class="container">
        <div class="nav">
            <div class="logo">
                <img src="images/logo.jpg">
            </div>
            <div class="nav-list">
                <a href="index.php">Home</a>
                <a href="about.php">About</a>
                <a href="services.php">Services</a>
                <a href="register.php">Register</a>
                <a href="contact.php">Contact</a>
            </div>
        </div>
   </div>